musicas/urls.py
from django.urls import path
from musicas.views import HomePage, MusicsPage

app_name='musicas'

urlpatterns = [
    path('', HomePage.as_view(), name= 'homepage'),
    path('<int:pk>', MusicsPage.as_view(), name='detail')
]

musicserver/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from musicas import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('musicas.urls')),
] #+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

musicas/models.py
from django.db import models
from musicas.helper import get_audio_length
from .validators import validate_is_audio
# Create your models here.




class Artista(models.Model):
    nome_artista = models.CharField(max_length=500)
    local_show = models.CharField(max_length=500)
    imagem = models.ImageField(upload_to='midia/', blank=False)



    def __str__(self):
        return (self.nome_artista + ' - ' + self.local_show)

class Faixa(models.Model):
    post = models.ForeignKey(Artista, default=None, on_delete=models.CASCADE)
    audio_file = models.FileField(upload_to='musics/', validators=[validate_is_audio])
    time_length = models.DecimalField(max_digits=20, decimal_places=2, blank=True)

    def __str__(self):
        return (self.post.nome_artista + self.post.local_show)

    def save(self,*args, **kwargs):
        if not self.time_length:
            # logic for getting length of audio
            audio_length=get_audio_length(self.audio_file)
            self.time_length = f'{audio_length:.2f}'

        return super().save(*args, **kwargs)

    class META:
        ordering="id"

musicas/views.py
from django.shortcuts import render, get_object_or_404
from .models import Artista, Faixa
from django.views.generic import ListView, DetailView




# Create your views here.
class HomePage(ListView):
    template_name = 'homepage.html'
    model = Artista
    print('homepage')


class MusicsPage(DetailView):
    template_name = "detail.html"
    model = Faixa
    musicas_do_artista = []

    def get(self, request, *arg, **kwargs):
        artista = self.get_object()  # pega o artista que esta sendo acessado
        musicas = list(Faixa.objects.filter(post=artista.pk).values())
        self.musicas_do_artista.clear()
        for mus in musicas:
            self.musicas_do_artista.append(mus['audio_file'])

        print("PRINTAaaaaaaaaa: ", self.musicas_do_artista)
        return super().get(request, *arg, *kwargs)  # redireciona pro link final


    def get_context_data(self, **kwargs):
            context = super().get_context_data(**kwargs)
            context["musicas_do_artista"] = self.musicas_do_artista
            print("PRINTA: ")
            return context

musicas/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">

	<head>
		<meta charset="America/Sao-Paulo">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		<title>{% block Title %}MusicFlix{% endblock Title %}</title>
		<meta name="description" content="">
		<meta name="keywords" content="">
		<meta name="author" content="">
		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

		<script src="https://cdn.tailwindcss.com"></script>
		<script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
		<script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>

		{% block head %}
		{% endblock %}


	</head>

	<body class="bg-black text-gray-100 font=primary">




		<div class="container-sm">

		{% block content %}

		{% endblock content %}

		</div>

	</body>

</html>

musicas/templates/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>meu site</h1>

{% for musica in musicas_do_artista %}
<h1>{{musica}}</h1>
<audio controls="controls" src="media/{{musica}}"></audio>
{% endfor %}

</body>
</html>

musicas/templates/homepage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>meu site</h1>

{% for artista in lista_forro %}
  {% if forloop.counter < 20 %}

          <a href="{% url 'musicas:detail' artista.pk %}">
            <img src="{{ artista.imagem.url }}">
          </a>

  {% endif %}
{% endfor %}

</body>
</html>